# See:
#  https://kubectl.docs.kubernetes.io/references/kustomize/
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# There must be agreement w/ the input resource name
# and the file produces within the post-renderer script
# (kustomize-post-renderer-hook.sh).
resources:
- all.yaml

patches:
  # Added due to a bug/configuration issues in jupyterhub-1.2.0.  The autohttps pod, which
  # in our deployments is responsible for auto-generating the TLS certificates used for
  # application ingress into the cluster, must wait a short period of time before attempting
  # to generate the certificate (letsencrypt).
  #
  # Although a helm value was introduced in the daskhub helm chart (2022.11.0), it executes
  # after the certificate generation has been attempted.  For this reason, we can't use it.
  #
  # See:
  #  https://discourse.jupyter.org/t/autohttps-pod-unable-to-obtain-lets-encrypt-certificate/15141
  - path: patch-jupyterhub-autohttps-startup-delay.yaml
    target:
      kind: Deployment
      name: autohttps

  # Added to ensure the daskhub application will retry generating the certificate if they
  # fail on the first attempt, which is likely due to the domain being registered at the
  # same time the cluster is created.  The default behavior of this deployment is to attempt
  # the cluster once on startup.  Adding a livenessProbes that verifies the contents of the
  # file '/etc/acme/acme.json' contains a reference to the certificate did the trick.
  #
  # Unfortunately, there is no value in the daskhub helm chart to date that allows adding
  # livenessProve to the first container in this deployments.  It's concievable that
  # subseqent revisions of the underlying container might handle retries more effectively
  # but until that's proven to be true, this patch should remain for all subseqent revisions
  # of daskhub.
  #
  # Here's what a /etc/acme/acme.json should look like on a healthy deployment.
  # {
  #   "default": {
  #     "Account": {
  #       ...
  #     },
  #     "Certificates": [
  #       {
  #         "domain": {
  #           "main": "<my-domain>"
  #       },
  #       ...
  #     }
  #   ]
  # }
  - target:
      kind: Deployment
      name: autohttps
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/livenessProbe
        value:
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
            exec:
              command: ["grep", "main", "/etc/acme/acme.json"]

  # Added when upgrading to kube-scheduler 1.26
  #  1.) This version only supports apiVersion v1beta3 or v1.  This configuration
  #      is defined in the ConfigMap.  There were a few additional changes within
  #      this resource as well.  The values included here are the current daskhub
  #      version 2024.1.1.
  #
  # Updated when upgrading to kube-scheduler 1.27
  #  1.) This version only supports apiVersion v1.  The first version of daskhub
  #      to support this apiVersion is 2024.1.0, these patches must remain until
  #      then
  - path: patch-jupyterhub-user-scheduler-configMap-apiVersion-v1.yaml
    target:
      kind: ConfigMap
      name: user-scheduler
