default_language_version:
  python: python3.13

repos:
  - repo: local
    hooks:
      - id: tofu-fmt
        name: tofu fmt
        entry: tofu fmt -recursive
        language: system
        pass_filenames: false
        files: \.(tf|tfvars|tftest\.hcl)$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
