ingress-nginx:
  controller:
    config:
      use-proxy-protocol: "false"
      use-forwarded-headers: "true"
      compute-full-forwarded-for: "true"
      large-client-header-buffers: "8 64k"
      client-header-buffer-size: "64k"
    ingressClassResource:
      name: nginx
      enabled: true
      default: true
    ingressClass: nginx
    service:
      targetPorts:
        http: http
        https: http
      ports:
        http: 80
        https: 443
      type: LoadBalancer # MUST remain LoadBalancer for ingress from Internet

oauth2-proxy:
  service:
    type: ClusterIP
    portNumber: 80
