ingress-nginx:
  controller:
    config:
      use-proxy-protocol: "false"
      use-forwarded-headers: "true"
      compute-full-forwarded-for: "true"
      large-client-header-buffers: "8 64k"
      client-header-buffer-size: "64k"
      proxy-body-size: "0"
    ingressClassResource:
      name: nginx
      enabled: true
      default: true
    ingressClass: nginx
    service:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
        service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
        service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
        service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
        service.beta.kubernetes.io/aws-load-balancer-attributes: "idle_timeout.timeout_seconds=120"
      targetPorts:
        http: http
        https: http
      ports:
        http: 80
        https: 443
      type: LoadBalancer

oauth2-proxy:
  service:
    type: ClusterIP
    portNumber: 80
  config:
    configFile: |-
      email_domains = [ "*" ]
      upstreams = [ "file:///dev/null" ]
  extraArgs:
    provider: oidc
    cookie-refresh: 30m
    scope: "openid profile email"
    set-authorization-header: true
    set-xauthrequest: true
    pass-user-headers: true
    prefer-email-to-user: false
    pass-authorization-header: true
    skip-auth-strip-headers: false
    pass-access-token: true
    cookie-samesite: "none"
    reverse-proxy: true
    cookie-secure: true
