# S3 buckets to use for storing data sets
# These will be configured as publicly visible, requestor pays, delete protected
public_data_buckets: [
  "edu-jhuapl-helio1",
  "edu-jhuapl-helio2",
  "edu-jhuapl-helio3"
]

# Registration upload bucket
# Will be configured as a private bucket visible only for internal HelioCloud upload processes
registration_upload_bucket: "edu-jhuapl-uploads"


