apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-persist
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: <<CNF_OUTPUT_EFSId>>.efs.{{ region }}.amazonaws.com
    path: "/"
