# Default configuration values to use for a HelioCloud deployment
# The HelioCloud CDK installer will use these values as a basis, applying any overrides
# specific in the instance configuration file provided by the deployer.

# AWS Environment (Optional)
# Specifies the AWS Account ID and Region into which this HelioCloud instance should be deployed.
# If values here are not overriden and left empty, the default behavior is to resolve these values
# from CDK Environment variables, which inherit them from the AWS CLI installation's configuration.
env:
  account: #Example: 123456781234
  region: # Example: us-east-1


# AWS VPC (Required)
# Specify the AWS VPC into which this HelioCloud instance should be deployed. Options are:
#   default - Use the default VPC for the AWS Account/Region to deploy into.
#   existing - Use an existing VPC in the AWS Account/Region having the provided vpc_id.
#   new - Create and use a new VPC in the AWS Account/Region using a set of sensible defaults required for a HelioCloud.
#       - No vpc_id need be provided then.
vpc:
  # Example: using the default VPC
  type: new
  # Example: If using existing vpc, place a vpc_id here. Other-wise this field is ignored.
  vpc_id: # example: vpc-0f10b7d51cd94cf4c #


# Shared S3 Bucket (Optional)
# Configuration options for the S3 bucket that is shared amongst users of this HelioCloud instance.
userSharedBucket:
  # Override to True to delete this S3 bucket when destroying the HelioCloud instance (via cdk destroy)
  destroyOnRemoval: False

# Email settings (Required - if using a custom email domain)
# Configuration for HelioCloud distributed emails.
email:
  # If False, the rest of the email settings are not considered
  use_custom_email_domain: False
  # Designates the username in "username@domain.com"
  user: "no-reply"
  # Designates the email sender name
  from_name: "APL HelioCloud"
  

# Authorization Settings (Required - if using Daskhub, User Dashboard)
# Configuration of the authorization services for a HelioCloud instance.
auth:
  # Cognito domain name prefix must be unique for all of AWS region
  domain_prefix: "apl-helio"

  # Indicates if deletion protection should be applied to this AWS resource,
  # it's recommended that this property be set to `True` for all Production
  # deployments.
  deletion_protection: True

  # Indicates the removal policy for this AWS resource when the stack is torn
  # down.  It's recommended that this property be set to `RETAIN` or `SNAPSHOT`
  # for all Production deployments.
  removal_policy: RETAIN

# HelioCloud Modules (Required)
# Enable/disable the installation of end-user modules in the HelioCloud instance.
# Defaulting to false, requiring deployers explicitly enable modules in their override config.
enabled:
  registry: False
  portal: False
  daskhub: False

# REGISTRY
# The registry is responsible for storing and accessible datasets stored in this HelioCloud instance.
# (REQUIRED) if enabled.registry is True
registry:

  # (REQUIRED): Names for public s3 buckets storing data sets (Required if enabled.registry is True)
  datasetBucketNames: [
    # example: s3://edu.myinstitution.myorganization
  ]

  # (OPTIONAL) Allows use of a specific name for the S3 bucket into which datasets may be uploaded for ingest
  # into a HelioCloud instance's Registry. Defaults to generated name, though consider providing a name
  # in development environments for simplicity.
  ingestBucketName: #Example: my.ingest.bucket

  # (OPTIONAL): Requires 3rd parties pay AWS egress costs to access data in this HelioCloud instance.
  # Defaults to true to ensure production HelioCloud instances don't incur undue expense when serving up the
  # data sets in their Registry to other HelioCloud instances or the scientific community at large.
  # Set to false if your organization is willing to incur these egress expenses.
  requesterPays: True

  # Settings for the catalog db - a database for storing registry information
  catalog:

    # (OPTIONAL): Name of the master administrative user for the AWS Document DB resource.
    # Note: password is automatically generated and stored in an AWS Secret
    masterUser: master

    # (OPTIONAL): Value to use when populating the name field of catalog.json at the root of each public s3 bucket
    name:

    # (OPTIONAL): Value ot use when populating the contact field of catalog.json at the root of each public s3 bucket
    contact:


  # (OPTIONAL): Typically, the catalog db and S3 buckets for ingest and data set storage should be retained even
  # on destruction of a HelioCloud instance, as these are likely to contain research data sets that shouldn't be lost.
  # Switching to True is useful in HelioCloud development.
  destroyOnRemoval: False

# User Portal (Required if enabled.portal is True)
portal:
  # portal will be hosted at <domain_record>.<domain_url>
  domain_url: #"myorganization-domain.org"
  domain_record: #"portal"
  domain_certificate_arn: #"arn:aws:acm:us-east-1:123456789012:certificate/abcdefg01-a0b0-c0f0-1mb09mf01fp1"

# Daskhub
# (Required if enabled.daskhub is True)
daskhub:









