# The following file is used for production deployments on GitLab.
#
# To run w/ this instance locally, type the following commands:
#   export CI_COMMIT_SHORT_SHA=<something>
#   envsubst < instance/gitlab-integration.yaml > instance/gitlab-integration-${CI_COMMIT_SHORT_SHA}.yaml
#
# Per-commit configurations should use: CI_COMMIT_SHORT_SHA
# Per-branch configurations should use: CI_COMMIT_REF_SLUG
#
#  See:
#   https://docs.gitlab.com/ee/ci/variables/predefined_variables.html

env:
  account: ${HC_AWS_ACCOUNT}
  region: ${AWS_DEFAULT_REGION}

# new VPC every time
vpc:
  type: new

userSharedBucket:
  destroyOnRemoval: False

email:
  use_custom_email_domain: True
  user: "no-reply"
  from_name: "APL HelioCloud"

# Only working on the registry right now
enabled:
  registry: True
  daskhub: True
  portal: True

auth:
  domain_prefix: "apl-helio"
  deletion_protection: True
  removal_policy: RETAIN

# Simple bucket names
registry:
  datasetBucketNames: [
    "heliocloud-production-${AWS_DEFAULT_REGION}-datasets-1",
  ]
  ingestBucketName: "heliocloud-production-${AWS_DEFAULT_REGION}-uploads-1"
  requesterPays: True
  catalog:
    masterUser: master
    name: "Chris Jeschke"
    contact: "chris.jeschke@jhuapl.edu"
  destroyOnRemoval: False
  layers:
    pandas: "arn:aws:lambda:${AWS_DEFAULT_REGION}:336392948345:layer:AWSSDKPandas-Python39:6"

portal:
  domain_url: "aplscicloud.org"
  domain_record: "portal"
  domain_certificate_arn: "arn:aws:acm:${AWS_DEFAULT_REGION}:${HC_AWS_ACCOUNT}:certificate/${HC_PORTAL_CERT_ARN}"

daskhub:
  # This is the IAM Role ARN that will be added to the aws-auth ConfigMap
  # that will be used to allow AWS Console users full access to the EKS cluster.
  EKS_CONSOLE_DASHBOARD_FULL_ACCESS_ROLE_ARN: "arn:aws:iam::${HC_AWS_ACCOUNT}:role/${HC_EKS_ROLE_ARN}"
  ROUTE53_HOSTED_ZONE: "aplscicloud.org"
  ROUTE53_DASKHUB_PREFIX: daskhub
  KUBERNETES_NAMESPACE: daskhub
  EKS_NAME: 'eks-helio'
  DASKHUB_ADMIN_USER: lenzinm1
  ADMIN_USER_EMAIL: nicholas.lenzi@jhuapl.edu
  GENERIC_DOCKER_LOCATION: 'public.ecr.aws/q3h7b4o8/helio-notebook'
  GENERIC_DOCKER_VERSION: '20230421'
  ML_DOCKER_LOCATION: 'public.ecr.aws/q3h7b4o8/helio-ml-notebook'
  ML_DOCKER_VERSION: '20230421'
