# The following file is used for production deployments on GitLab.
#
# To run w/ this instance locally, type the following commands:
#   export CI_COMMIT_SHORT_SHA=<something>
#   envsubst < instance/gitlab-integration.yaml > instance/gitlab-integration-${CI_COMMIT_SHORT_SHA}.yaml
#
# Per-commit configurations should use: CI_COMMIT_SHORT_SHA
# Per-branch configurations should use: CI_COMMIT_REF_SLUG
#
#  See:
#   https://docs.gitlab.com/ee/ci/variables/predefined_variables.html

env:
  account: ${HC_AWS_ACCOUNT}
  region: ${AWS_DEFAULT_REGION}

# new VPC every time
vpc:
  type: new

userSharedBucket:
  destroyOnRemoval: False

email:
  use_custom_email_domain: True
  user: "no-reply"
  from_name: "APL HelioCloud"

enabled:
  registry: False
  daskhub: True
  daskhub_metrics: True
  portal: True
  registration_page: False

auth:
  domain_prefix: "apl-helio"
  deletion_protection: True
  removal_policy: RETAIN

portal:
  domain_url: "aplscicloud.org"
  domain_record: "portal"
  domain_certificate_arn: "arn:aws:acm:${AWS_DEFAULT_REGION}:${HC_AWS_ACCOUNT}:certificate/${HC_PORTAL_CERT_ARN}"

registration_page:
  domain_url: "aplscicloud.org"
  domain_record: "registration"
  domain_certificate_arn: "arn:aws:acm:${AWS_DEFAULT_REGION}:${HC_AWS_ACCOUNT}:certificate/${HC_PORTAL_CERT_ARN}"

daskhub:
  eksctl:
    metadata:
      name: 'eks-helio'
      region: '${AWS_DEFAULT_REGION}'
    availabilityZones:
    - ${AWS_DEFAULT_REGION}a
    - ${AWS_DEFAULT_REGION}b
    iamIdentityMappings:
      - arn: arn:aws:iam::${HC_AWS_ACCOUNT}:role/CT-PowerUser-HelioCloud
        groups:
        - eks-console-dashboard-full-access-group
      - arn: arn:aws:iam::${HC_AWS_ACCOUNT}:user/CT-PowerUser-HelioCloud-nicholas.lenzi@jhuapl.edu-401
        groups:
        - eks-console-dashboard-full-access-group
        - daskhub-admin-access-group
        - monitoring-admin-access-group
        username: lenzinm1
  daskhub_storage:
    efs-persist:
      storage: 10000Gi

  daskhub:
    namespace: daskhub
    api_key1: auto
    api_key2: auto
    admin_users:
     - lenzinm1
    contact_email: nicholas.lenzi@jhuapl.edu

    GENERIC_DOCKER_LOCATION: 'public.ecr.aws/q3h7b4o8/heliocloud/helio-daskhub-core'
    GENERIC_DOCKER_VERSION: '2025.01.23'
    MLTF_DOCKER_LOCATION: 'public.ecr.aws/q3h7b4o8/heliocloud/helio-daskhub-mltf'
    MLTF_DOCKER_VERSION: '2025.01.23'
    MLTRCH_DOCKER_LOCATION: 'public.ecr.aws/q3h7b4o8/heliocloud/helio-daskhub-mltrch'
    MLTRCH_DOCKER_VERSION: '2025.01.23'

    domain_url: "aplscicloud.org"
    domain_record: "daskhub"

  monitoring:
    AWS_LOAD_BALANCER_SSL_CERT: "arn:aws:acm:${AWS_DEFAULT_REGION}:${HC_AWS_ACCOUNT}:certificate/${HC_PORTAL_CERT_ARN}"
    grafana_domain_prefix: grafana
    cost_analyzer_domain_prefix: kubecost
