# The following file is used for deploying to the staging environment on GitLab.
#
# To run w/ this instance locally, type the following commands:
#   export CI_COMMIT_SHORT_SHA=<something>
#   envsubst < instance/gitlab-integration.yaml > instance/gitlab-integration-${CI_COMMIT_SHORT_SHA}.yaml
#
# Per-commit configurations should use: CI_COMMIT_SHORT_SHA
# Per-branch configurations should use: CI_COMMIT_REF_SLUG
#
#  See:
#   https://docs.gitlab.com/ee/ci/variables/predefined_variables.html

env:
  account: ${HC_AWS_ACCOUNT}
  region: ${AWS_DEFAULT_REGION}

# new VPC every time
vpc:
  type: new

# Destroying so we can clean up dev
userSharedBucket:
  destroyOnRemoval: True

email:
  use_custom_email_domain: True
  user: "no-reply"
  from_name: "DEV - APL HelioCloud"

# Only working on the registry right now
enabled:
  registry: True
  daskhub: True
  daskhub_metrics: True
  portal: True

auth:
  domain_prefix: "apl-helio"
  deletion_protection: True
  removal_policy: RETAIN

# Simple bucket names
registry:
  datasetBucketNames: [
     "heliocloud-staging-${AWS_DEFAULT_REGION}-datasets-1",
  ]

  ingestBucketName: "heliocloud-staging-${AWS_DEFAULT_REGION}-uploads-1"
  requesterPays: True
  catalog:
    masterUser: master
    name: "Chris Jeschke"
    contact: "chris.jeschke@jhuapl.edu"
  destroyOnRemoval: True
  layers:
    pandas: "arn:aws:lambda:${AWS_DEFAULT_REGION}:336392948345:layer:AWSSDKPandas-Python39:6"

portal:
  domain_url: "aplscicloud.org"
  domain_record: "portal-dev"
  domain_certificate_arn: "arn:aws:acm:${AWS_DEFAULT_REGION}:${HC_AWS_ACCOUNT}:certificate/${HC_PORTAL_CERT_ARN}"

daskhub:
  eksctl:
    metadata:
      name: 'eks-helio'
      region: '${AWS_DEFAULT_REGION}'
    availabilityZones:
    - ${AWS_DEFAULT_REGION}a
    - ${AWS_DEFAULT_REGION}b
    iamIdentityMappings:
      - arn: arn:aws:iam::${HC_AWS_ACCOUNT}:role/CT-PowerUser-HelioCloud
        groups:
        - eks-console-dashboard-full-access-group
      - arn: arn:aws:iam::${HC_AWS_ACCOUNT}:user/CT-PowerUser-HelioCloud-nicholas.lenzi@jhuapl.edu-401
        groups:
        - eks-console-dashboard-full-access-group
        - daskhub-admin-access-group
        username: lenzinm1
    nodeGroups:
      # ng-user-gpu
      - instancesDistribution:
          instanceTypes:
            - "g4dn.4xlarge"
      # ng-user-compute
      - instancesDistribution:
          instanceTypes:
            - "m5.4xlarge"
            - "m5n.4xlarge"
            - "m5d.4xlarge"
            - "m5dn.4xlarge"
      # ng-burst-compute-spot
      - instancesDistribution:
          instanceTypes:
            - "m5n.8xlarge"
            - "m5.8xlarge"
            - "m4.8xlarge"
            - "m5dn.8xlarge"
            - "r5n.8xlarge"
            - "r5dn.8xlarge"
  daskhub_storage:
    efs-persist:
      storage: 10000Gi

  daskhub:
    namespace: daskhub
    api_key1: add55be357c8eed7fe79663591cbe41270e51fc2bc6fcb23afc8beb5a29f4acc
    api_key2: c6a52b9090ea7ce7df6da06bf8f7e882c531441d93e482c1cbb28ad4a401aebe
    admin_users:
     - lenzinm1
    contact_email: nicholas.lenzi@jhuapl.edu

    GENERIC_DOCKER_LOCATION: 'public.ecr.aws/q3h7b4o8/heliocloud/helio-notebook'
    GENERIC_DOCKER_VERSION: '2023.12.06'
    ML_DOCKER_LOCATION: 'public.ecr.aws/q3h7b4o8/heliocloud/helio-notebook-mltf'
    ML_DOCKER_VERSION: '2023.12.06'

    domain_url: "aplscicloud.org"
    domain_record: "daskhub-dev"

  monitoring:
    AWS_LOAD_BALANCER_SSL_CERT: "arn:aws:acm:${AWS_DEFAULT_REGION}:${HC_AWS_ACCOUNT}:certificate/${HC_PORTAL_CERT_ARN}"

daskhub_metrics:
  domain_url: "aplscicloud.org"
  grafana_domain_prefix: grafana-dev-${AWS_DEFAULT_REGION}
  prometheus_domain_prefix: prometheus-dev-${AWS_DEFAULT_REGION}
  AWS_LOAD_BALANCER_SSL_CERT: "arn:aws:acm:${AWS_DEFAULT_REGION}:${HC_AWS_ACCOUNT}:certificate/${HC_PORTAL_CERT_ARN}"
