# Overrides for cjeschke's dev environment

# Existing cjeschke-dev VPC
vpc:
  type: existing
  vpc_id: vpc-0d3c0a227894442bb

# Only run the registry for now
components:
  enableRegistry: True
  enableUserDashboard: False
  enableDaskHub: False

# Simple bucket names
registry:
  bucketNames: [
    "cjeschke-dev-datasets"
  ]
  destroyOnRemoval: True
  requesterPays: True
  uploadBucketName : "cjeschke-dev-uploads"



