# Configuration file to use be used during a HelioCloud installation

# Components to enable in the installation
components:
  enableRegistry: True
  enableUserDashboard: True
  enableDaskHub: True

# Details for the registry component
# S3 data_sets to use for storing data sets
# These will be configured as publicly visible, requestor pays, delete protected
registry:
  bucketNames: [
    "edu-jhuapl-helio1",
    "edu-jhuapl-helio2",
    "edu-jhuapl-helio3"
  ]
  # Optional: Defaults to False.
  # Enabling makes (re)deployments of a HelioCloud easier during development & testing
  destroyOnRemoval: True

  # Optional: Defaults to True,
  # Can be disabled here with the caveat that the AWS account hosting this HelioCloud instance will be responsible
  # for ALL egress costs out of these PUBLIC S3 buckets (re: HIGH RISK).
  requesterPays: True

# Config block for user dashboard settings
userDashboard:

# Config block for the Daskhub
daskhub:







