kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: efs-scratch-space
  namespace: daskhub
spec:
  storageClassName: "efs"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
