apiVersion: v1
data:
  cluster.name: ${EKS_NAME}
  http.port: "2020"
  http.server: "On"
  logs.region: ${AWS_REGION}
  read.head: "Off"
  read.tail: "On"
kind: ConfigMap
metadata:
  name: fluent-bit-cluster-info
  namespace: amazon-cloudwatch
