apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: daskhub-admin-access-role
  namespace: daskhub
rules:
- apiGroups:
  - ""
  - "*"
  resources:
  - "*"
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: daskhub-admin-access-binding
  namespace: daskhub
subjects:
- kind: Group
  name: daskhub-admin-access-group
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: daskhub-admin-access-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: daskhub-admin-access-clusterrole
rules:
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - clusterroles
  - clusterrolebindings
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: daskhub-admin-access-clusterrolebinding
subjects:
- kind: Group
  name: daskhub-admin-access-group
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: daskhub-admin-access-clusterrole
  apiGroup: rbac.authorization.k8s.io