cost-analyzer:
  service:
    type: ClusterIP
    port: 9090
    targetPort: 9090
  forecasting:
    enabled: false
  grafana:
    service:
      type: ClusterIP
      port: 80
    grafana.ini:
      auth.anonymous:
        enabled: true
    livenessProbe:
      httpGet:
        path: /healthz
        port: 3000
      initialDelaySeconds: 15
      periodSeconds: 20
    readinessProbe:
      httpGet:
        path: /healthz
        port: 3000
      initialDelaySeconds: 15
      periodSeconds: 20
