# -- FILE: features/daskhub_server_launch.feature

@Daskhub
Feature: Log into daskhub, launch a server and do stuff

  Scenario:  Create a user account to run this suite of tests.
    Given a fully deployed instance of HelioCloud
     Then create a user with the name "helioptile"

  Scenario:  Attempt to access the daskhub server spawn page
    Given a fully deployed instance of HelioCloud
     Then go to the "daskhub-login-page"
      And verify the "daskhub-login-page"
      And wait 5 seconds
      And enter "helioptile" in the "username" field
      And enter the password in the "password" field
      And click "Sign in"
      And verify the "daskhub-server_spawn-page"

  Scenario: Spawn a server
    Given a fully deployed instance of HelioCloud
      And the user is logged in
      And the user is on the "daskhub-server_spawn-page"
     Then click "Server"
      And click "Start"
      And verify the "daskhub-main-page"
      And wait 30 seconds

  Scenario: Stop My Server and Logout of Daskhub
    Given a fully deployed instance of HelioCloud
      And the user is logged in
    Then go to the "daskhub-home-page"
      And click "Stop My Server"
      And wait 30 seconds
      And click "Logout"

  @Cleanup
  Scenario:  Remove all K8 resources generated by this test
    Given a fully deployed instance of HelioCloud
      And no existing pod named "jupyter-helioptile" exists in namespace "daskhub"

  @Cleanup
  Scenario:  Delete the user account that ran with this suite of tests.
    Given a fully deployed instance of HelioCloud
     Then delete a user with the name "helioptile"
