# -- FILE: features/daskhub_server_launch.feature

@Daskhub @JupyterServer
Feature: Log into daskhub, launch a server and do stuff

  Scenario:  Create a user account to run this suite of tests.
    Given a fully deployed instance of HelioCloud
     Then create a user with the name "helioptile"

  Scenario:  Attempt to access the daskhub server spawn page
    Given a fully deployed instance of HelioCloud
     Then go to the "daskhub-login-page"
      And verify the "daskhub-login-page"
      And wait 5 seconds
      And enter "helioptile" in the "username" field
      And enter the password in the "password" field
      And click "Sign in"
      And verify the "daskhub-server_spawn-page"

  Scenario Outline: Spawn a server
    Given a fully deployed instance of HelioCloud
      And the user is logged in
      And the user is on the "daskhub-server_spawn-page"
     Then click "<server_name>"
      And click "Start"
      And verify the "daskhub-main-page"
      And wait 30 seconds
      And take a screenshot with name "daskhub-main-page-server-spawn-<server-type>.png"
    Then go to the "daskhub-home-page"
      And wait 2 seconds
      And click "Stop My Server"
      And wait 30 seconds
      And click "Logout"

    Examples:
      |      server_name         | server_type            |
      | Server                   | server                 |
      | The Big Big Server       | the-big-big-server     |
      | GPU Server - PyTorch     | gpu-server-pytorch     |
      | GPU Server - Tensor Flow | gpu-server-tensor-flow |
      
  @Cleanup
  Scenario:  Remove all K8 resources generated by this test
    Given a fully deployed instance of HelioCloud
      And no existing pod named "jupyter-helioptile" exists in namespace "daskhub"

  @Cleanup
  Scenario:  Delete the user account that ran with this suite of tests.
    Given a fully deployed instance of HelioCloud
     Then delete a user with the name "helioptile"
