@Daskhub @JupyterNotebook
Feature: Log into daskhub, launch a server and do stuff

  Scenario:  Create a user account to run this suite of tests.
    Given a fully deployed instance of HelioCloud
     Then create a user with the name "helioptile"

  Scenario:  Attempt to access the daskhub server spawn page
    Given a fully deployed instance of HelioCloud
     Then go to the "daskhub-login-page"
      And verify the "daskhub-login-page"
      And wait 5 seconds
      And enter "helioptile" in the "username" field
      And enter the password in the "password" field
      And click "Sign in"
      And verify the "daskhub-server_spawn-page"

  Scenario: Spawn a server
    Given a fully deployed instance of HelioCloud
      And the user is logged in
      And the user is on the "daskhub-server_spawn-page"
     Then click "Server"
      And click "Start"
      And verify the "daskhub-main-page"
      And wait 30 seconds

  Scenario Outline: Run the Jupyter Notebook
    Given a fully deployed instance of HelioCloud
      And the user is logged in
     Then go to the "daskhub-classic-page"
      And click folder item "<folder>"
      And click folder item "<notebook>"
      And take a screenshot with name "daskhub-classic-notebook-<notebook>.png"
      And click "restart the kernel, then re-run the whole notebook (with dialog)"
      And click "Restart and Run All Cells"
      And wait up to <max_wait_time> seconds for execution to complete

    Examples:
      |      folder       |         notebook           | max_wait_time |
      | science-tutorials | 01-Intro-Tutorial.ipynb    |            15 |
      | science-tutorials | CloudCatalog-Demo.ipynb    |            60 |
      | science-tutorials | Dask-Gateway-Example.ipynb |           450 |
      | science-tutorials | HelioCloud-SDO-Demo.ipynb  |          1200 |
      | science-tutorials | MMS-Catalog-Demo.ipynb     |            30 |
      | science-tutorials | S3-Access-Demo.ipynb       |            30 |
      | science-tutorials | S3-Dask-Demo.ipynb         |           450 |

  Scenario: Stop My Server and Logout of Daskhub
    Given a fully deployed instance of HelioCloud
      And the user is logged in
    Then go to the "daskhub-home-page"
      And click "Stop My Server"
      And wait 30 seconds
      And click "Logout"

  @Cleanup
  Scenario:  Remove all K8 resources generated by this test
    Given a fully deployed instance of HelioCloud
      And no existing pod named "jupyter-helioptile" exists in namespace "daskhub"

  @Cleanup
  Scenario:  Delete the user account that ran with this suite of tests.
    Given a fully deployed instance of HelioCloud
     Then delete a user with the name "helioptile"
