# Default configuration values to use for a HelioCloud deployment
# The HelioCloud CDK installer will use these values as a basis, applying any overrides
# specific by the runtime configuration file provided by the user


# Specify the VPC into which all HelioCloud resources will be deployed. Options are:
#   default - Use the default VPC for the AWS account. This will be resolved automatically.
#   existing - Use an existing VPC in the AWS account. The vpc_id must be provided for the lookup.
#   new - A new VPC will be created for your HelioCloud instance using a set of sensible defaults intended
#         to meet HelioCloud resource requirements.
vpc:
  # Default to the default VPC of this AWS account
  type: default
  # If using EXISTING, place your VPC ID here. Otherwise, this field is ignored.
  vpc_id: # example: vpc-0f10b7d51cd94cf4c #

# Settings for the shared user bucket
userSharedBucket:
  destroyOnRemoval: False

# Configuration block for the Authorization stack. This is automatically installed if authorization
# capabilities are required by the components enabled below (Registry, Daskhub, Dashboard, etc)
auth:
  # Cognito domain name prefix must be unique for all of AWS region
  domain_prefix: "apl-helio"


# Enabled/Disable optional HelioCloud modules
enabled:
  registry: False
  userDashboard: False
  daskhub: False


# REGISTRY component of a HelioCloud instance
# The Registry is used for storing and making accessible various data sets to this HelioCloud instance
# as well as any other instances participating in the greater HelioCloud "network". Data stored here
# is placed in public s3 buckets for access by other HelioClouds.
registry:

  # REQUIRED: Must have a list of S3 bucket names to use to store registered data sets.
  # This should be provided via an override config.
  bucketNames: [
                # example: s3://edu.myinstitution.myorganization
               ]

  # OPTIONAL: Defaults to False.
  # Enabling makes (re)deployments of a HelioCloud easier during development & testing
  destroyOnRemoval: False

  # OPTIONAL: Defaults to True,
  # Can be disabled here with the caveat that the AWS account hosting this HelioCloud instance will be responsible
  # for ALL egress costs out of these PUBLIC S3 buckets (re: HIGH RISK).
  requesterPays: True

# USER DASHBOARD component of a HelioCloud instance
# TODO: need a good writeup
userDashboard:

# DASKHUB component of a HelioCloud instance
# TODO: need a good writeup
daskhub:









