apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-helio
  region: us-west-1

iamIdentityMappings:
  - arn: "<<INSERT>>"
    username: admin
    groups:
    - system:masters
    - eks-console-dashboard-full-access-group
    - kube-system-admin-access-group
    - daskhub-admin-access-group
    - monitoring-admin-access-group
