# See:
#  https://kubectl.docs.kubernetes.io/references/kustomize/
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- clusterautoscaler.yaml
- eks-console-full-access.yaml
- external-dns.yaml
